// Generated by Wrangler by running `wrangler types --env example`

interface Env {
	OAUTH_KV: KVNamespace;
	WORKOS_CLIENT_ID: string;
	WORKOS_CLIENT_SECRET: string;
	MCP_OBJECT: DurableObjectNamespace /* MyMCP */;
	AI: Ai;
}
